"""Master phrase library for Atlas Cortex filler system.

Contains all filler phrases grouped by sentiment and purpose.  Other modules
import from here instead of defining their own pools.

Architecture:
  - **STREAM_FILLERS** — short text phrases yielded as the first token before
    the LLM generates.  Injected into the system prompt so the LLM continues
    naturally from them.  End with a trailing space or " — ".
  - **AUDIO_FILLERS** — longer phrases (~4–6 s spoken) pre-synthesized to TTS
    audio at startup.  Played over the satellite speaker while the LLM works.
  - **MICRO_ACK_*** — very short "thinking" sounds injected during long pauses.

Startup caching:
  Only the first ``PRECACHE_PER_SENTIMENT`` audio fillers per sentiment are
  pre-synthesized at startup.  The rest are available for on-demand (lazy)
  synthesis the first time they're selected.
"""

from __future__ import annotations

# How many audio fillers to pre-synthesize per sentiment at startup.
# The rest are lazy-cached on first use.
PRECACHE_PER_SENTIMENT = 50

# =====================================================================
#  STREAM FILLERS — short text (prepended to LLM response)
# =====================================================================

STREAM_FILLERS: dict[str, list[str]] = {

    # ── question (150+) ──────────────────────────────────────────
    "question": [
        # "Let me" pattern
        "Let me check. ",
        "Let me think. ",
        "Let me look into that. ",
        "Let me see. ",
        "Let me find out. ",
        "Let me pull that up. ",
        "Let me dig into that. ",
        "Let me figure this out. ",
        "Let me look that up. ",
        "Let me work through this. ",
        "Let me piece that together. ",
        "Let me recall. ",
        "Let me think about that. ",
        "Let me consider that. ",
        "Let me see what I know. ",
        "Let me check on that. ",
        "Let me get that for you. ",
        "Let me sort through that. ",
        "Let me run through this. ",
        "Let me put this together. ",
        # "Hmm" pattern
        "Hmm, one moment. ",
        "Hmm, let me think. ",
        "Hmm, good one. ",
        "Hmm, interesting. ",
        "Hmm, let me see here. ",
        "Hmm, that's a thought. ",
        "Hmm, okay. ",
        "Hmm, working on it. ",
        "Hmm, hold on. ",
        "Hmm, give me a sec. ",
        "Hmm, let me figure that out. ",
        "Hmm, yeah. ",
        "Hmm, I know this. ",
        "Hmm, fair question. ",
        # "Good question" pattern
        "Good question, one sec. ",
        "Good question, let me think. ",
        "Good one. ",
        "That's a good question. ",
        "Great question. ",
        "Nice question. ",
        "Fair question. ",
        "Valid question. ",
        "Interesting question. ",
        "Smart question. ",
        # Interjections
        "Ooh, let me check. ",
        "Ah, right. ",
        "Oh! I think I know. ",
        "Ooh, okay. ",
        "Ah, let me think. ",
        "Oh, good one. ",
        "Ooh, that's interesting. ",
        "Ha, okay. ",
        "Oh yeah. ",
        "Ah, I see. ",
        # Time references
        "One moment. ",
        "One sec. ",
        "Just a moment. ",
        "Give me a second. ",
        "Hang on. ",
        "Just a sec. ",
        "Moment. ",
        "Quick sec. ",
        "Two seconds. ",
        "Half a moment. ",
        # Self-talk
        "Thinking... ",
        "Processing... ",
        "Working on it. ",
        "On it. ",
        "Checking. ",
        "Looking into it. ",
        "Pulling that up. ",
        "Digging in. ",
        "Running through it. ",
        "Sorting through this. ",
        "Putting it together. ",
        "Figuring this out. ",
        "Got it, thinking. ",
        "Right, let me think. ",
        "Okay, processing. ",
        # Conversational
        "I know this one. ",
        "I've got this. ",
        "I think I know. ",
        "This is a fun one. ",
        "That rings a bell. ",
        "I was just thinking about this. ",
        "Off the top of my head — ",
        "From what I recall — ",
        "If I'm remembering right — ",
        "I believe — ",
        "Okay, so — ",
        "Right, so — ",
        "Well — ",
        "Alright, so — ",
        "Here's the thing — ",
        "So basically — ",
        # Brief markers
        "Sure — ",
        "Right — ",
        "Okay — ",
        "Yeah — ",
        "Yep — ",
        "Mhm — ",
        "Gotcha — ",
        "Ah — ",
        "So — ",
        "Mm — ",
        # Playful
        "Ooh, I like this question. ",
        "Now that's a good one. ",
        "You've got me thinking. ",
        "This one's fun. ",
        "Challenge accepted. ",
        "I was hoping you'd ask that. ",
        "Always wanted to answer this. ",
        "Glad you asked. ",
        "You're making me think. ",
        "Solid question. ",
        # Direct acknowledgment
        "Understood. ",
        "Got it. ",
        "Copy that. ",
        "Heard you. ",
        "Roger. ",
        "I'm on it. ",
        "Working on that now. ",
        "Already on it. ",
        "Absolutely, let me look. ",
        "For sure. ",
        # Additional variety
        "Let me see what comes up. ",
        "Bear with me. ",
        "Let me noodle on that. ",
        "That's worth looking into. ",
        "Lemme think here. ",
        "Okay okay okay. ",
        "Alright alright. ",
        "Just pulling my thoughts together. ",
        "Quick think. ",
        "Hold that thought. ",
        "Okay, I've got something. ",
        "I can work with that. ",
        "Let me spin that around. ",
        "Sketching it out. ",
        "Mapping it out. ",
        "Give me a beat. ",
        "Let me zero in. ",
        "Narrowing it down. ",
        "I've got a lead. ",
        "Tracking it down. ",
        "On the trail. ",
        "Let me connect the dots. ",
        "Putting the pieces together. ",
        "Wheels are turning. ",
        "Almost got it. ",
    ],

    # ── greeting (150+) ──────────────────────────────────────────
    "greeting": [
        # Basic greetings
        "Hey! ",
        "Hey there! ",
        "Hi! ",
        "Hi there! ",
        "Hello! ",
        "Hey hey! ",
        "Yo! ",
        "Howdy! ",
        "What's up! ",
        "Sup! ",
        # Time-based
        "Morning! ",
        "Good morning! ",
        "Afternoon! ",
        "Good afternoon! ",
        "Evening! ",
        "Good evening! ",
        "Top of the morning! ",
        # Warm greetings
        "Hey, good to hear from you! ",
        "There you are! ",
        "Hey friend! ",
        "Hey, what's going on? ",
        "Hey, how's it going? ",
        "Hey! What can I do? ",
        "Hey, what's happening? ",
        "Hey! Nice to hear you. ",
        "Hey, I'm here! ",
        "Hello hello! ",
        "Well hello! ",
        "Oh hey! ",
        "Hey, welcome back! ",
        "Good to see you! ",
        "Back again! ",
        "Hey you! ",
        "Look who it is! ",
        "Hey, what brings you? ",
        # Enthusiastic
        "Hey! Let me help. ",
        "Hi! I'm ready. ",
        "Hey there! What do you need? ",
        "Hey! Let me check. ",
        "Hi! Let me see. ",
        "Hey! I'm all ears. ",
        "Hello! I'm listening. ",
        "Hey! Fire away. ",
        "Hi! Go ahead. ",
        "Hey! Hit me. ",
        "Hey! What do you got? ",
        "Hello! What's on your mind? ",
        "Hey! I'm here for you. ",
        "Hi! Let me look into that. ",
        "Hey! I was just thinking. ",
        # Casual greetings
        "What can I help with? ",
        "How can I help? ",
        "What do you need? ",
        "I'm all yours. ",
        "At your service. ",
        "Standing by. ",
        "Ready when you are. ",
        "I'm listening. ",
        "Shoot. ",
        "Go for it. ",
        "I'm here. ",
        "Lay it on me. ",
        "What's the question? ",
        "What do we got? ",
        "Talk to me. ",
        "I'm on it. ",
        "Ready to roll. ",
        "Fire away. ",
        "Let's hear it. ",
        "Let's go. ",
        # Conversational
        "Oh hi! One sec. ",
        "Hey hey, let me check. ",
        "Well hello there! ",
        "Oh, hi! ",
        "Hey! Funny you asked. ",
        "Hey! Glad you're here. ",
        "Oh! Hey there. ",
        "Hi! Perfect timing. ",
        "Hey there, one moment. ",
        "Hello! Give me just a second. ",
        "Hi there! Let me see. ",
        "Hey! Bear with me. ",
        "Hello! Just a sec. ",
        "Hey! Thinking. ",
        "Hi! Hmm. ",
        # Brief
        "Hey — ",
        "Hi — ",
        "Hello — ",
        "Heya — ",
        "Yo — ",
        "Hey hey — ",
        "Oh hey — ",
        "Well hey — ",
        "Ah, hey — ",
        "Hi hi — ",
        # Returning user
        "Hey again! ",
        "Oh, you're back! ",
        "Welcome back! ",
        "Hey, round two! ",
        "Back for more? ",
        "Hey again, what's up? ",
        "Hi again! ",
        "And we're back! ",
        "Oh hey, welcome back! ",
        "Good to have you back! ",
        # Playful
        "Well well well. ",
        "Look at you. ",
        "Hey, fancy seeing you here. ",
        "Why hello. ",
        "Oh hi, I was just here. ",
        "Hey, what's cooking? ",
        "Hey, what's the scoop? ",
        "Hey, what's new? ",
        "Hey, long time no see! ",
        "Hey, there's a face I know! ",
        # Extra variety
        "Hey! Something I can help with? ",
        "Hi! I'm right here. ",
        "Hey! What's the situation? ",
        "Hello! Let's do this. ",
        "Hey! You know where to find me. ",
        "Hi! Always here. ",
        "Hey! Pull up a chair. ",
        "Hello there! ",
        "Why hello there! ",
        "Hey! Let me think. ",
        "Hi! Working on it. ",
        "Hey! Let's see here. ",
        "Hello! Let me pull that up. ",
        "Hey! Quick sec. ",
        "Hi! One moment. ",
        "Hey! I gotcha. ",
        "Hello! Gotcha. ",
        "Hey! You got it. ",
        "Hi! Coming right up. ",
        "Hey! Let me get that. ",
        "Hey! Need a hand? ",
        "Hello! At your service. ",
        "Hey! Right here. ",
        "Hi! Reporting for duty. ",
        "Hey! Let's figure it out. ",
        "Hello! I'm on the case. ",
        "Hey! Glad to help. ",
        "Hi! Let's get into it. ",
        "Hey! Step right up. ",
        "Hello! What can I find? ",
        "Hey! Ask away. ",
        "Hi! What's the word? ",
        "Hey! I'm game. ",
        "Hello! Bring it. ",
        "Hey! You've come to the right place. ",
    ],

    # ── frustrated (100+) ────────────────────────────────────────
    "frustrated": [
        # Empathetic + action
        "I hear you. Let me look. ",
        "I hear you. Let me check. ",
        "I understand. Let me see. ",
        "I get it. Let me help. ",
        "Got it. Let me fix this. ",
        "I hear ya. Let me dig in. ",
        "Understood. Let me check on that. ",
        "Fair enough. Let me look. ",
        "I totally get that. Let me see. ",
        "Yeah, I hear you. ",
        "I know, I know. Let me help. ",
        "Makes sense you're frustrated. Let me look. ",
        "No worries, I'm on it. ",
        "Okay, I'm gonna sort this out. ",
        "Let me take care of this. ",
        # Reassuring
        "Let me see what I can do. ",
        "Let me figure this out for you. ",
        "Let me get to the bottom of this. ",
        "Let me straighten this out. ",
        "Let me work through this. ",
        "Let me sort this out. ",
        "I'll get this handled. ",
        "I'm going to fix this. ",
        "Leave it with me. ",
        "I've got this. ",
        "I'll take care of it. ",
        "Let me make this right. ",
        "We'll get this figured out. ",
        "Let me find a solution. ",
        "Working on it right now. ",
        # Empathy first
        "That's annoying, I know. ",
        "Yeah, that's not great. ",
        "Ugh, sorry about that. ",
        "I feel you on that. ",
        "That's fair. ",
        "You're right to be frustrated. ",
        "I wouldn't like that either. ",
        "That does sound frustrating. ",
        "I can see why that's annoying. ",
        "Not ideal, I know. ",
        # Direct action
        "On it. ",
        "Right away. ",
        "I'm looking into it now. ",
        "Checking now. ",
        "Give me just a second. ",
        "Let me jump on that. ",
        "I'm all over it. ",
        "Hang on, I'm checking. ",
        "Let me dig into that right away. ",
        "Working on a fix. ",
        # Validating
        "Totally understand. Let me check. ",
        "That makes sense. One sec. ",
        "Yep, that's a pain. Let me help. ",
        "Completely fair. Let me see. ",
        "I get where you're coming from. ",
        "You're not wrong. Let me look. ",
        "Valid. Let me check on that. ",
        "That's legit frustrating. ",
        "I'd be annoyed too. Let me see. ",
        "Yeah, no, I get it. ",
        # Calm redirection
        "Okay, deep breath. Let me help. ",
        "Let's take this one step at a time. ",
        "I'm gonna get this sorted. ",
        "Let's figure this out together. ",
        "One thing at a time. Let me look. ",
        "We'll get there. Let me check. ",
        "I promise I'll try to help. ",
        "I'm here for this. Let me look. ",
        "Let me see what happened. ",
        "Let me find out what's going on. ",
        # Accountability
        "Okay, let me see where things went wrong. ",
        "Let me look into what happened. ",
        "Let me trace this back. ",
        "Let me check what's going on. ",
        "Something's off — let me look. ",
        "Let me investigate. ",
        "Give me a moment to check. ",
        "Let me get some clarity on this. ",
        "I want to understand what went wrong. ",
        "Let me review this. ",
        # Brief empathetic
        "I'm sorry. Let me help. ",
        "My bad. Let me fix this. ",
        "Sorry about that. ",
        "That sucks. Let me help. ",
        "Not cool. Let me check. ",
        "Ugh. Let me see. ",
        "Hmm, that shouldn't happen. ",
        "Yeah, that's not right. ",
        "Okay, that's no good. ",
        "Right. Let me look at that. ",
        # Additional
        "I want to make this better. ",
        "Let me do what I can. ",
        "I'm gonna try my best here. ",
        "Let me see if I can help with that. ",
        "Alright, let me take a crack at this. ",
        "Don't worry, I'm looking. ",
        "I'm already on it. ",
        "Bear with me, I'm checking. ",
        "This is fixable. Let me look. ",
        "Let me see what our options are. ",
    ],

    # ── excited (100+) ───────────────────────────────────────────
    "excited": [
        # Enthusiastic + action
        "Oh nice! Let me check. ",
        "Love it! One sec. ",
        "Let me see! ",
        "Ooh! Let me look. ",
        "Sweet! Let me check. ",
        "Awesome! Let me see. ",
        "Oh cool! One moment. ",
        "Nice! Let me find out. ",
        "Yes! Let me check on that. ",
        "Oh fun! Let me see. ",
        # High energy
        "That's exciting! ",
        "I love that idea! ",
        "Oh that's great! ",
        "What a great idea! ",
        "Brilliant! ",
        "I'm into it! ",
        "That sounds amazing! ",
        "Oh man, yes! ",
        "Heck yeah! ",
        "Now we're talking! ",
        # Enthusiastic agreement
        "Love that. Let me check. ",
        "I'm so into this. ",
        "Oh, this is gonna be good. ",
        "I like where this is going. ",
        "This is awesome. ",
        "Oh yeah, absolutely. ",
        "Count me in. Let me look. ",
        "I am HERE for this. ",
        "This is the best. ",
        "You've got great taste. ",
        # Playful
        "Oooh, spicy! ",
        "Oooh, I like it. ",
        "Now THAT'S a question. ",
        "Oh, fun one. ",
        "That's what I'm talking about. ",
        "Music to my ears. ",
        "Keep talking. Let me check. ",
        "Tell me more — actually, let me look first. ",
        "Ooh la la. Let me see. ",
        "That's the spirit! Let me check. ",
        # Positive + action
        "Great choice! Let me pull that up. ",
        "Good call! Let me see. ",
        "Smart move. Let me check. ",
        "Oh perfect. Let me look into that. ",
        "Excellent. Let me find out. ",
        "Fantastic. Give me a sec. ",
        "Wonderful. Let me check. ",
        "Beautiful. One moment. ",
        "Gorgeous question. Let me check. ",
        "Oh that's lovely. Let me see. ",
        # Brief enthusiasm
        "Ooh! ",
        "Nice! ",
        "Sweet! ",
        "Yes! ",
        "Awesome! ",
        "Love it! ",
        "Oh yeah! ",
        "Heck yes! ",
        "Alright! ",
        "Woo! ",
        # Conversational excitement
        "Oh, I know exactly what you mean. ",
        "I was just thinking about this! ",
        "Great minds think alike. ",
        "You and me both! Let me check. ",
        "Oh, me too! Let me look. ",
        "I've been wanting to try that. ",
        "That's on my list too! ",
        "I'm excited about this one. ",
        "This is right up my alley. ",
        "Oh, I have thoughts on this. ",
        # Energized acknowledgment
        "Can't wait to help with this. ",
        "Oh, this'll be fun. ",
        "I'm fired up. Let me check. ",
        "Bring it on! Let me look. ",
        "Let's do this! ",
        "Let's gooo. ",
        "Oh we are so doing this. ",
        "Buckle up. Let me check. ",
        "Ready for this. Let me see. ",
        "Oh this is gonna be great. ",
        # Warm enthusiasm
        "That sounds wonderful. Let me check. ",
        "How exciting! Let me look. ",
        "Oh how fun! One sec. ",
        "That's so cool. Let me see. ",
        "I love it. Let me check. ",
        "That's fantastic. Let me look into it. ",
        "Super cool. Let me see. ",
        "How neat. Let me check. ",
        "Oh my gosh, yes. Let me look. ",
        "That makes me happy. Let me check. ",
        # Extra
        "Oh, absolutely. ",
        "For sure. Let me check. ",
        "You bet. Let me look. ",
        "Totally! One sec. ",
        "Definitely! Let me see. ",
        "Oh, a hundred percent. Let me look. ",
        "Yes yes yes. Let me check. ",
        "Oh, no doubt. Let me see. ",
        "Absolutely. Give me a sec. ",
        "Without a doubt. Let me look. ",
    ],

    # ── late_night (100+) ────────────────────────────────────────
    "late_night": [
        # Calm acknowledgments
        "Let me check. ",
        "One moment. ",
        "Let me take a look. ",
        "Let me see. ",
        "Hmm, let me look. ",
        "Checking. ",
        "Sure, one sec. ",
        "Give me a moment. ",
        "Let me look into that. ",
        "Let me see here. ",
        # Quiet energy
        "Alright, let me check. ",
        "Okay, let me see. ",
        "Mm, let me look. ",
        "Right, one moment. ",
        "Sure thing. ",
        "Gotcha. ",
        "Understood. ",
        "Got it. ",
        "Mhm. ",
        "Mm, okay. ",
        # Night-aware
        "Still up? Let me check. ",
        "Late one, huh? Let me see. ",
        "Burning the midnight oil. Let me look. ",
        "Night owl mode. Let me check. ",
        "Can't sleep? Let me help. ",
        "You and me both. Let me check. ",
        "The quiet hours. Let me look. ",
        "Just us night owls. Let me see. ",
        "Late night question, huh? ",
        "Midnight thoughts. Let me check. ",
        # Gentle
        "Sure, let me take a peek. ",
        "Of course. Let me look. ",
        "Happy to help. Let me check. ",
        "No problem. Let me see. ",
        "Absolutely. One moment. ",
        "You got it. Let me look. ",
        "I'm here. Let me check. ",
        "Always up. Let me see. ",
        "I don't sleep. Let me check. ",
        "24/7. Let me look. ",
        # Mellow
        "Hmm. ",
        "Let me think. ",
        "One sec. ",
        "Thinking. ",
        "Working on it. ",
        "On it. ",
        "Checking on that. ",
        "Looking into it. ",
        "Pulling that up. ",
        "Running through it. ",
        # Warm + quiet
        "Alright, alright. Let me check. ",
        "Okay, let me figure this out. ",
        "Hmm, give me just a sec. ",
        "Let me piece this together. ",
        "Sure, working on it. ",
        "Let me noodle on that. ",
        "Hmm, okay, let me think. ",
        "Right. Thinking. ",
        "Mm, hold on. ",
        "Alright, bear with me. ",
        # Brief
        "Sure — ",
        "Right — ",
        "Okay — ",
        "Mm — ",
        "Hmm — ",
        "Yeah — ",
        "Gotcha — ",
        "Mhm — ",
        "Alright — ",
        "Yep — ",
        # Conversational calm
        "Fair question. Let me think. ",
        "Interesting. Let me check. ",
        "Good point. Let me look. ",
        "I see what you mean. ",
        "That's a thought. Let me check. ",
        "You've got me thinking. ",
        "Hmm, I like that question. ",
        "Let me consider that. ",
        "Good one. Let me think. ",
        "Let me mull that over. ",
        # Relaxed variety
        "Let me see what I can find. ",
        "Gimme a sec. ",
        "Hold on a tick. ",
        "Let me poke around. ",
        "Lemme see. ",
        "Just a tick. ",
        "Hold that thought. ",
        "Let me chew on that. ",
        "Hmm, processing. ",
        "Let me get my thoughts together. ",
        # Extra
        "Quiet time question. Let me see. ",
        "Good late-night thought. ",
        "Late night brain working. Let me check. ",
        "I'm always thinking. Let me look. ",
        "Never too late to ask. Let me check. ",
        "Anytime. Let me see. ",
        "I'm a night person too. Let me check. ",
        "The world's quieter now. Let me think. ",
        "No rush. Let me check. ",
        "Take it easy. Let me look. ",
    ],

    # ── follow_up (100+) ─────────────────────────────────────────
    "follow_up": [
        # Continuation markers
        "Right — ",
        "Okay — ",
        "Sure thing. ",
        "Gotcha — ",
        "Understood — ",
        "Yeah — ",
        "Yep — ",
        "Mm — ",
        "Mhm — ",
        "Ah — ",
        # Acknowledging continuation
        "Good follow-up. ",
        "Fair point. ",
        "Good point. ",
        "True. ",
        "Interesting. ",
        "I see. ",
        "Makes sense. ",
        "Got it. ",
        "Okay, so — ",
        "Alright, so — ",
        # Deeper dive
        "Let me dig a bit deeper. ",
        "Let me look into that more. ",
        "Let me expand on that. ",
        "Let me go further. ",
        "Going deeper. ",
        "Diving in more. ",
        "Let me elaborate. ",
        "Good, let me continue. ",
        "Building on that. ",
        "Adding to that. ",
        # Conversational
        "So following up on that — ",
        "Continuing from where we were — ",
        "To add to what I said — ",
        "On that note — ",
        "Along those lines — ",
        "Speaking of which — ",
        "Related to that — ",
        "To build on that — ",
        "In that vein — ",
        "While we're on the topic — ",
        # Thinking further
        "Hmm, and — ",
        "Actually — ",
        "Come to think of it — ",
        "Oh, and also — ",
        "One more thing — ",
        "Plus — ",
        "And — ",
        "Also — ",
        "Furthermore — ",
        "Additionally — ",
        # Clarification
        "Let me clarify. ",
        "To be more specific — ",
        "What I mean is — ",
        "Put another way — ",
        "In other words — ",
        "To elaborate — ",
        "More precisely — ",
        "Specifically — ",
        "To break it down — ",
        "Here's the detail — ",
        # Agreement + continuation
        "Exactly. ",
        "Spot on. ",
        "You're right. ",
        "That's correct. ",
        "Bingo. ",
        "Nailed it. ",
        "Precisely. ",
        "That's it. ",
        "On the money. ",
        "Right on. ",
        # Redirect
        "Well actually — ",
        "Hmm, not quite — ",
        "Close, but — ",
        "Sort of — ",
        "Kind of — ",
        "In a way — ",
        "Partially — ",
        "Yes and no — ",
        "It depends — ",
        "That's complicated — ",
        # Engaged continuation
        "Oh, great question. ",
        "I was hoping you'd ask that. ",
        "Glad you brought that up. ",
        "Good, you're thinking about this. ",
        "Now we're getting somewhere. ",
        "Ooh, now it gets interesting. ",
        "Ah, the plot thickens. ",
        "Now that's the real question. ",
        "Digging deeper, I like it. ",
        "You're on the right track. ",
        # Brief
        "Sure — ",
        "So — ",
        "Well — ",
        "Now — ",
        "Then — ",
        "Next — ",
        "And so — ",
        "From there — ",
        "Moving on — ",
        "Continuing — ",
    ],

    # ── command (50+) ─────────────────────────────────────────────
    "command": [
        "On it. ",
        "Sure thing. ",
        "You got it. ",
        "Done. ",
        "Consider it done. ",
        "Right away. ",
        "Doing it now. ",
        "Will do. ",
        "Of course. ",
        "Absolutely. ",
        "No problem. ",
        "Sure. ",
        "Got it. ",
        "Gotcha. ",
        "Understood. ",
        "Copy that. ",
        "Roger. ",
        "Yep. ",
        "Yeah. ",
        "Okay. ",
        "Alright. ",
        "Coming right up. ",
        "On my way. ",
        "Working on it. ",
        "Already on it. ",
        "Say no more. ",
        "Consider it handled. ",
        "I'm on it. ",
        "Taking care of it. ",
        "Just a moment. ",
        "One sec. ",
        "Here we go. ",
        "Let's do it. ",
        "Handling that now. ",
        "Right on it. ",
        "Yep, doing it. ",
        "Easy. ",
        "No sweat. ",
        "Can do. ",
        "You bet. ",
        "Gladly. ",
        "Happy to. ",
        "My pleasure. ",
        "With pleasure. ",
        "Certainly. ",
        "For sure. ",
        "Totally. ",
        "Affirmative. ",
        "As you wish. ",
        "Right. ",
        "Check. ",
        "All over it. ",
        "On the case. ",
        "Making it happen. ",
        "Let me handle that. ",
    ],

    # ── casual (100+) ────────────────────────────────────────────
    "casual": [
        # Light conversation
        "Oh hey. ",
        "So anyway — ",
        "Well — ",
        "Hm — ",
        "Yeah, so — ",
        "You know — ",
        "I mean — ",
        "Thing is — ",
        "Here's the deal — ",
        "Funny you mention that — ",
        # Thinking aloud
        "Hmm. ",
        "Let me think. ",
        "Let me see. ",
        "Huh. ",
        "Interesting. ",
        "Oh. ",
        "Ah. ",
        "Well well. ",
        "Now let's see. ",
        "Okay so. ",
        # Conversational fillers
        "I was just thinking about that. ",
        "Funny story — ",
        "Speaking of which — ",
        "That reminds me — ",
        "Come to think of it — ",
        "You know what — ",
        "Actually — ",
        "To be honest — ",
        "If you ask me — ",
        "In my experience — ",
        # Light acknowledgment
        "Sure sure. ",
        "Yeah yeah. ",
        "Right right. ",
        "Okay okay. ",
        "Fair fair. ",
        "True true. ",
        "Makes sense. ",
        "I see. ",
        "Gotcha. ",
        "Word. ",
        # Casual engagement
        "Oh nice. ",
        "Cool. ",
        "Neat. ",
        "How about that. ",
        "I dig it. ",
        "Solid. ",
        "Sweet. ",
        "Not bad. ",
        "Fair enough. ",
        "Can't argue with that. ",
        # Conversational warmth
        "Ha, yeah. ",
        "Ha, fair point. ",
        "Heh, true. ",
        "Yeah, I feel that. ",
        "I know, right? ",
        "Tell me about it. ",
        "Been there. ",
        "Same honestly. ",
        "I get that. ",
        "Totally. ",
        # Musing
        "Now that's a thought. ",
        "Huh, never thought about it that way. ",
        "That's one way to look at it. ",
        "You might be onto something. ",
        "There's something to that. ",
        "I could see that. ",
        "That tracks. ",
        "Makes you think. ",
        "I wonder. ",
        "Good point though. ",
        # Brief
        "Oh — ",
        "Hmm now — ",
        "So — ",
        "Anyway — ",
        "Alright — ",
        "Okay — ",
        "Right — ",
        "Yeah — ",
        "Well then — ",
        "Look — ",
        # Relaxed
        "No rush. ",
        "Take your time. ",
        "We're good. ",
        "All good. ",
        "Easy does it. ",
        "No worries. ",
        "Chill. ",
        "Relax. ",
        "Easy peasy. ",
        "Smooth sailing. ",
        # Extra variety
        "Oh you know me. ",
        "Classic question. ",
        "That old chestnut. ",
        "An oldie but goodie. ",
        "The eternal question. ",
        "People ask me that a lot. ",
        "I get that one all the time. ",
        "Now there's a topic. ",
        "Buckle up — ",
        "Here we go — ",
    ],
}


# =====================================================================
#  AUDIO FILLERS — longer phrases (~4–6 s spoken, pre-synthesized)
# =====================================================================

AUDIO_FILLERS: dict[str, list[str]] = {

    # ── question (150+) ──────────────────────────────────────────
    "question": [
        "Good question — let me think about that for just a moment.",
        "Hmm, let me look into that for you.",
        "Alright, let me pull that together for you real quick.",
        "Sure thing, let me see what I can find on that.",
        "That's a great question, give me just a second.",
        "Let me dig into that and see what comes up.",
        "Okay, one moment while I check on that for you.",
        "Hang on, let me find that out for you.",
        "Let me think on that — I want to give you a good answer.",
        "Bear with me for just a moment while I look that up.",
        "Oh, that's a fun one. Let me see what I've got.",
        "Hmm, I think I know the answer to this. Let me double check.",
        "Let me pull my thoughts together on that real quick.",
        "That's actually a really interesting question — one moment.",
        "Okay, let me see if I can give you a clear answer on this.",
        "Give me just a beat — I want to get this right for you.",
        "Ooh, good one. Let me think about that for a second.",
        "Let me run through what I know on that real quick.",
        "Alright, that's worth looking into. Bear with me.",
        "Let me piece that together for you — shouldn't take long.",
        "Hmm, yeah, that's a thoughtful question. One sec.",
        "I want to be accurate here — let me check on that.",
        "You know what, let me make sure I've got this right.",
        "Let me see — I think I know where to find that.",
        "Okay, working through that in my head right now.",
        "That's a solid question. Give me a quick moment.",
        "Let me chew on that for just a second.",
        "Interesting — let me think about how to explain this.",
        "Hold on, I'm pretty sure I know this. Let me confirm.",
        "Let me take a quick look and get back to you on that.",
        "Hmm, let me sift through what I know about that.",
        "That's the kind of question I like. Give me a moment.",
        "Okay, I want to answer this well — just a second.",
        "Let me see what the best answer is here.",
        "Oh, I've got a thought. Let me work it out.",
        "Let me figure out the clearest way to explain that.",
        "Sure, I'll check on that right now.",
        "That's an interesting angle. Let me look into it.",
        "Right, let me think through this step by step.",
        "Give me a moment — I want to make sure I'm being helpful.",
        "Alright, let me see what we're working with here.",
        "Hmm, that requires a bit of thought. Just a sec.",
        "Let me connect the dots on that one for you.",
        "Hold tight — I think I can help with this.",
        "Let me rummage through my brain on this one.",
        "Oh yeah, I know something about that. Let me think.",
        "Okay, let me recall what I know about this.",
        "I've seen this before — let me pull up the details.",
        "Good question. I need to think about that carefully.",
        "Let me find the right way to put this.",
        "Hmm, I know there's a good answer here somewhere.",
        "Let me work through that — it's a nuanced one.",
        "Sure, give me a quick beat to figure this out.",
        "That's making me think. Hold on a sec.",
        "Let me see — there are a few angles on this.",
        "Alright, I'm pulling that together now.",
        "Let me chase down the answer to that one.",
        "Hmm, I think I can help. Just working it out.",
        "Okay, processing. Give me one moment.",
        "Let me think about how to frame this answer.",
        "That's a thinker. Give me just a second.",
        "Okay, hold on — I'm working through it.",
        "Hmm, let me approach this from the right angle.",
        "I want to give you a useful answer — one sec.",
        "Let me take a beat and think through this properly.",
        "Ooh, I like that question. Let me dig in.",
        "Let me think about that from a couple different angles.",
        "Alright, let me get my ducks in a row on this.",
        "Give me a sec — I'm sorting through what I know.",
        "Let me find the best way to answer that for you.",
        "Hmm, there's a lot to unpack there. One moment.",
        "That's worth a careful answer. Bear with me.",
        "Let me see if I can zero in on what you're asking.",
        "Good one — let me take a second to think.",
        "Okay, let me mull that over real quick.",
        "Let me bring up what I know about that.",
        "Alright, give me a moment to collect my thoughts.",
        "That's an excellent question — I need a beat.",
        "Let me trace through the answer on this.",
        "Sure, I'll work on that. Just a moment.",
        "I have some thoughts on that — let me organize them.",
        "Hmm, let me see if I can be precise about this.",
        "Okay, give me a quick sec — I'm thinking.",
        "Let me walk through this in my head first.",
        "That deserves a good answer. One moment, please.",
        "Let me gather my thoughts before I answer.",
        "Hmm, I need to think about this one carefully.",
        "Bear with me — I want to give you something useful.",
        "Let me turn that over in my mind for a second.",
        "Alright, I've got ideas. Let me sort them.",
        "Hmm, let me consider the best way to explain that.",
        "That's going to take a moment of thought — hang on.",
        "Let me puzzle through that for you.",
        "Okay, I'm on it. Just need a quick moment.",
        "Let me think about that — it's a fair question.",
        "Oh, that's a meaty one. Let me think.",
        "Let me see if I can crack that for you.",
        "Hmm, that's making my gears turn. One sec.",
        "I think I've got something — let me flesh it out.",
        "Let me reason through that real quick.",
        "Okay, that's a layered question. Let me dig in.",
        "Give me a sec to think about the best way to put this.",
        "Alright, I'm chewing on that right now.",
        "Hmm, let me look at this from your perspective.",
        "Let me work out the details on that for you.",
        "That's actually something I find interesting — one moment.",
        "Let me see — I think I can shed some light on that.",
        "Okay, let me process that for a second.",
        "Hmm, let me try to untangle that for you.",
        "I'm thinking about that right now. Give me a sec.",
        "Let me make sure I answer what you're actually asking.",
        "Let me sift through that and find the key point.",
        "Okay, I have a hunch. Let me verify it.",
        "Hmm, I know there's a clear answer — let me find it.",
        "Let me think about what would actually be helpful here.",
        "Right, let me put on my thinking cap for this one.",
        "Okay, I want to explain this well. One second.",
        "Let me run through a few possibilities on that.",
        "Hmm, give me a beat — I think I can nail this.",
        "That's a question worth answering properly. Hang on.",
        "Let me zoom in on what you need to know.",
        "Alright, let me tackle that one for you.",
        "Hmm, there's a nuance here. Let me sort it out.",
        "Give me just a moment — I'm zeroing in on the answer.",
        "Let me think about the most helpful response to that.",
        "Okay, that's got me thinking. One moment.",
        "Let me find the thread and follow it for you.",
        "Hmm, I need a second to think through this one.",
        "Let me see what I can put together for you on that.",
        "Okay, I'm almost there — just working out the details.",
        "Let me check my facts before I give you an answer.",
        "That's a great thing to wonder about. One sec.",
        "Let me unpack that question for a second.",
        "Alright, I think I can help. Just need to think.",
        "Let me go through this methodically for you.",
        "Hmm, I've got competing thoughts — let me sort them.",
        "Bear with me for a beat — almost got it.",
        "Let me work through the logic on that real quick.",
        "Okay, let me see what makes the most sense here.",
        "That's making me think hard. Give me just a sec.",
        "Let me get a clear picture before I answer.",
        "Hmm, let me triangulate on the right answer.",
        "I want to be thoughtful about this — one moment.",
        "Let me see — I think I can connect this together.",
        "Alright, let me brain through this one.",
        "Okay, I'm thinking. Give me a quick second.",
        "Let me try to get to the heart of that for you.",
    ],

    # ── greeting (50) ────────────────────────────────────────────
    "greeting": [
        "Hey there! Give me just a second.",
        "Hey! Let me see what I can help you with.",
        "Good to hear from you! Let me check on that.",
        "Hey there! Let me pull that together for you.",
        "Oh hey! Let me see what I can find.",
        "Hello! Let me take a look at that for you.",
        "Hey! Great to hear your voice. One moment.",
        "Hey there! Sure thing — let me check on that.",
        "Hi! I'm on it — give me just a second.",
        "Hey! I've got you — let me look into that.",
        "Oh, hey there! Let me think about that.",
        "Hey! You caught me at a good time. Let me check.",
        "Hello there! Give me a moment to look into that.",
        "Hey! Alright, let me see what I can do.",
        "Oh, hi! Let me dig into that for you.",
        "Hey hey! Bear with me for just a second.",
        "Oh, hello! Let me pull that up real quick.",
        "Hey! I think I can help with that. One sec.",
        "Hi there! Let me get right on that for you.",
        "Hey! Perfect question. Let me check.",
        "Good to see you! Let me take a look.",
        "Well hello! Let me see what we've got.",
        "Hey there! Working on it right now.",
        "Hi! Let me figure that out for you.",
        "Hey! Always happy to help. One moment.",
        "Oh hi! Let me see about that.",
        "Hey there! I'm already looking into it.",
        "Hello hello! Let me check on that for you.",
        "Hey! Interesting — let me see what I know.",
        "Hey there! Hmm, let me think on that.",
        "Hi! That's a good one — give me a sec.",
        "Hey! Let me work through that for you.",
        "Hello! Absolutely — let me find out.",
        "Hey there! I'm curious too — let me check.",
        "Hi! Okay, let me run through that.",
        "Hey! Good question to start with. Let me look.",
        "Oh, hey! I was hoping someone would ask that.",
        "Hey there! Let me sort that out for you.",
        "Hello! Sure, give me just a moment.",
        "Hey! I think I've got something. Let me check.",
        "Hey there! Let me round up what I know.",
        "Hi! Hmm, interesting. Let me look into it.",
        "Hey! I'll get right on that for you.",
        "Hello! Let me put my thinking cap on.",
        "Hey there! Okay, one moment while I look.",
        "Hey! Let me see — I think I know this one.",
        "Hi! Working on it — just a quick second.",
        "Hey! Oh that's fun. Let me check.",
        "Hey there! Let me grab that info for you.",
        "Hello! Great question — bear with me a sec.",
    ],

    # ── frustrated (50) ──────────────────────────────────────────
    "frustrated": [
        "I hear you — let me look into that right away.",
        "Okay, let me see what I can do about that for you.",
        "I understand your frustration — let me help sort this out.",
        "Let me get to the bottom of this for you right now.",
        "I know that's frustrating — bear with me while I check.",
        "Sorry about that — let me take a closer look for you.",
        "Okay, that's not great. Let me see what I can figure out.",
        "I get it — let me see if there's something I can do.",
        "That's fair — let me dig into what's going on.",
        "I don't blame you. Let me look into that immediately.",
        "Alright, I'm going to try and get this sorted for you.",
        "I hear you — let me find a way to help with that.",
        "Okay, let me work on fixing that right away.",
        "I know it's annoying — give me a moment to look.",
        "Let me take care of this — I want to make it right.",
        "I'm on it — let me figure out what went wrong.",
        "Totally valid. Let me check into that for you.",
        "That shouldn't be happening — let me investigate.",
        "I want to help fix this — give me just a moment.",
        "I can see why that's frustrating. Let me look.",
        "Hang on — let me see if I can make this better.",
        "Okay, I'm going to prioritize this. One moment.",
        "I feel you on that — let me check what's going on.",
        "Let me find out what happened and see what we can do.",
        "Absolutely, I'll look into that right now for you.",
        "I know that's not ideal. Let me see what I can find.",
        "Bear with me — I'm going to try to straighten this out.",
        "I get where you're coming from. Let me take a look.",
        "Let me make sure we get this right this time around.",
        "Okay, that needs attention. Let me check on it.",
        "I understand. Let me see what the situation is.",
        "Sorry you're dealing with that — let me help out.",
        "Hmm, that's no good. Let me see what's going on.",
        "I hear the frustration. Let me work on this for you.",
        "Let me look at this carefully — I want to help.",
        "Okay, give me a second to see what we can do here.",
        "I don't want you to be stuck. Let me figure this out.",
        "Right, I'm going to focus on getting this resolved.",
        "Let me put some thought into sorting this out for you.",
        "I know that's been a hassle. Let me check into it.",
        "Let me take a careful look and see what I can find.",
        "Okay, this clearly matters to you. I'm on it.",
        "I want to make this less painful — one moment.",
        "Let me see if there's a quick fix for that.",
        "Alright, I'm looking into this as we speak.",
        "I'm going to do my best to help with that right now.",
        "Let me trace through what happened and find a solution.",
        "That's worth fixing. Let me see what I can do.",
        "I hear you loud and clear — let me check on that.",
        "I'll do everything I can here. Give me a sec.",
    ],

    # ── excited (50) ─────────────────────────────────────────────
    "excited": [
        "Oh, nice! Let me check on that for you.",
        "That sounds great — let me pull that up.",
        "Ooh, I love that! Let me see what I can find.",
        "That's awesome! Give me just a second to look.",
        "Oh fun! Let me dig into that for you.",
        "I'm excited about this one too! Let me check.",
        "Oh that's great — bear with me while I look.",
        "Yes! I think I can help with that. One moment.",
        "Oh, love it! Let me see what I've got for you.",
        "That's a great idea — let me look into it.",
        "This is going to be fun. Let me check on that.",
        "Ooh, I've been wanting to look into that! One sec.",
        "How exciting! Let me see what I can find out.",
        "Oh, that's right up my alley. Let me check.",
        "I can't wait to help with this one! Hang on.",
        "Oh that's cool — let me pull something together.",
        "This is gonna be great. Give me a moment.",
        "Ooh, interesting choice! Let me look into it.",
        "I love where your head's at. Let me check.",
        "Now that's something special — let me see.",
        "Oh, what a great thing to explore! One moment.",
        "That's fantastic — let me get on that for you.",
        "Ooh, yes! Let me dive in on that one.",
        "How cool is that! Let me see what I can find.",
        "I'm totally here for this. Let me check.",
        "Oh, that's a winner. Let me look into it.",
        "Great pick! Let me see what I can pull up.",
        "Ooh, I have thoughts on this! Give me a sec.",
        "That's wonderful — let me see what I know.",
        "Oh nice — I think you're going to like what I find.",
        "Love that question! Let me think about it.",
        "That's my kind of question. Let me dig in.",
        "Alright, this is gonna be good! Let me look.",
        "Oh I'm into this. Give me a moment.",
        "What a fun thing to ask about! Let me check.",
        "Oh yes — I've been hoping someone would bring that up.",
        "This is the kind of stuff I love. One moment.",
        "I'm pumped about this one! Let me look.",
        "That's a great one — let me see what I've got.",
        "Oh, absolutely! Let me find that out for you.",
        "You've got great taste! Let me check on that.",
        "Ooh, now you're talking! Let me look into it.",
        "I love it — let me see what comes up.",
        "Oh, what a lovely question. Give me a moment.",
        "This one's exciting! Let me figure it out.",
        "Yes yes yes — let me check on that for you.",
        "Oh how fun! Let me pull something together.",
        "That's stellar — let me see what I can find.",
        "I'm all in on this. Let me look real quick.",
        "Ooh, buckle up! Let me check on that.",
    ],

    # ── late_night (50) ──────────────────────────────────────────
    "late_night": [
        "Alright, let me take a look at that for you.",
        "Sure thing, one moment while I check.",
        "Hmm, let me think about that for a moment.",
        "Okay, let me see what I can find on that.",
        "Let me check on that — shouldn't take long.",
        "Give me a moment — I'll look into it.",
        "Sure, let me dig into that for you.",
        "Hmm, let me pull that together. One sec.",
        "Alright, let me see what we've got here.",
        "Okay, bear with me while I look into that.",
        "Let me think on that — I want to get it right.",
        "Hmm, interesting thought. Let me check.",
        "Let me take a quiet moment to figure this out.",
        "Sure, let me work through that for you.",
        "Alright, let me piece that together.",
        "Okay, give me a moment — I'm thinking.",
        "Let me see — I think I know the answer to that.",
        "Hmm, let me turn that over for a second.",
        "Let me look at that carefully for you.",
        "Alright, just a moment while I sort that out.",
        "Hmm, let me find the best way to answer that.",
        "Let me take my time on this one — it's a good question.",
        "Okay, I'll check on that right now.",
        "Let me see what I can put together for you.",
        "Hmm, let me mull that over for a quick second.",
        "Alright, let me look into it nice and easy.",
        "Sure, no rush. Let me figure that out.",
        "Let me think through that at a calm pace.",
        "Hmm, let me sift through what I know.",
        "Okay, let me collect my thoughts on this.",
        "Let me ease into that one — good question.",
        "Alright, working on it for you now.",
        "Hmm, let me look at this from a few angles.",
        "Let me quietly work through this for you.",
        "Okay, give me a gentle moment to think.",
        "Let me take a look — the night is patient.",
        "Hmm, late night brain is on it. One sec.",
        "Alright, let me ponder that for just a moment.",
        "Sure thing, let me chew on that for a bit.",
        "Let me see — I think I can help with that.",
        "Okay, I'm noodling on this right now.",
        "Hmm, let me approach this thoughtfully.",
        "Let me sit with that question for a moment.",
        "Alright, give me a sec — it's a thinker.",
        "Let me gently pull that info together.",
        "Hmm, let me slowly work through that.",
        "Okay, night mode thinking engaged. One moment.",
        "Let me take a measured look at that for you.",
        "Hmm, let me ease into the answer on this one.",
        "Alright, let me calmly sort that out.",
    ],
}


# =====================================================================
#  MICRO-ACK PHRASES — very short "thinking" sounds
# =====================================================================

MICRO_ACK_CASUAL: list[str] = [
    "Hmm...",
    "Let me see...",
    "One moment...",
    "Mm-hmm...",
    "Thinking...",
    "Hmm, okay...",
    "Let me think...",
    "Hold on...",
    "One sec...",
    "Working on it...",
    "Checking...",
    "Looking...",
    "Hmm, yeah...",
    "Processing...",
    "Give me a sec...",
    "Just a moment...",
    "Okay...",
    "Right...",
    "Let me look...",
    "Mm, let me see...",
    "Oh, hmm...",
    "Ah, right...",
    "Uh-huh...",
    "Mm, okay...",
    "Let me check...",
    "Hang on...",
    "Pulling that up...",
    "Running through it...",
    "Sorting it out...",
    "Piecing it together...",
    "Hmm, interesting...",
    "Still thinking...",
    "Working through it...",
    "Getting there...",
    "Ah, let me see...",
    "Okay, okay...",
    "Right, right...",
    "Hmm hmm...",
    "Yeah, thinking...",
    "Just a tick...",
    "Bear with me...",
    "Moment...",
    "Quick sec...",
    "Almost...",
    "Let me just...",
    "Hmm, so...",
    "Thinking on it...",
    "Turning it over...",
    "Considering...",
    "Mulling...",
    "Noodling on it...",
    "Chewing on that...",
]

MICRO_ACK_REASSURING: list[str] = [
    "Almost there...",
    "Still working on that...",
    "Just a bit more...",
    "Bear with me...",
    "Getting close...",
    "Nearly there...",
    "Shouldn't be long now...",
    "Almost got it...",
    "Working through it...",
    "Hang in there...",
    "Just about done...",
    "One more moment...",
    "Getting it together...",
    "Still on it...",
    "Making progress...",
    "Coming together...",
    "Wrapping it up...",
    "Close now...",
    "Pulling it together...",
    "Stay with me...",
    "Almost done thinking...",
    "Finishing up...",
    "Just about there...",
    "Hold tight, almost...",
    "Right around the corner...",
    "Any second now...",
    "Narrowing it down...",
    "Zeroing in...",
    "Locking it in...",
    "Just polishing the thought...",
    "Got the pieces, connecting them...",
    "It's coming together...",
    "Just need a moment more...",
    "Almost have it...",
    "On the home stretch...",
    "Final thought coming...",
    "Just sorting the last bit...",
    "The answer's forming...",
    "Working out the details...",
    "Think I've got it...",
    "Piecing it all together now...",
    "Tying it all up...",
    "One last check...",
    "Running through the last bit...",
    "Putting the final touches...",
    "I think I see it now...",
    "It's crystallizing...",
    "Just about locked in...",
    "Final stretch...",
    "And... almost...",
]

MICRO_ACK_COMPLEX: list[str] = [
    "That's a big question...",
    "Lots to consider here...",
    "Digging deeper...",
    "There's a lot to unpack...",
    "This one needs some thought...",
    "Complex question...",
    "Layered question...",
    "Multiple angles on this...",
    "Gotta think carefully...",
    "There's nuance here...",
    "A few things at play...",
    "This is a deep one...",
    "Rich question...",
    "That's multi-layered...",
    "Several factors here...",
    "Need to weigh a few things...",
    "Lots of moving parts...",
    "That requires careful thought...",
    "Many sides to this...",
    "A real thinker...",
    "Meaty question...",
    "Substantive one...",
    "That goes deep...",
    "There are trade-offs...",
    "It's not straightforward...",
    "There's context to consider...",
    "Depends on a few things...",
    "Need to factor in a lot...",
    "That's got layers...",
    "A proper brain-teaser...",
    "This one takes a minute...",
]
