"""Simple Self-Distillation (SSD) — Apple arxiv.org/abs/2604.01193.

The model generates code samples at varied temperatures, filters for valid
Python outputs, fine-tunes a LoRA on its own best work, evaluates against
a held-out set, and promotes the adapter only when improvement exceeds a
configurable threshold.  Designed as the *lowest-priority* nightly evolution
job — it only runs when the GPU is idle and no other evolution work is queued.

Each iteration builds on the previous LoRA (iterative distillation), so
improvements compound across nights.
"""

# Module ownership: Self-distillation (SSD) nightly evolution job

from __future__ import annotations

import ast
import json
import logging
import os
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import aiohttp

from cortex.db import get_db

log = logging.getLogger(__name__)

# ── Environment / configuration ──────────────────────────────────────

_ENV_PREFIX = "SSD_"

_DEFAULTS: dict[str, Any] = {
    "ENABLED": True,
    "SAMPLES_PER_PROBLEM": 25,
    "TEMPERATURES": [0.6, 0.8, 1.0],
    "MIN_IMPROVEMENT": 0.02,
    "MAX_ITERATIONS": 100,
    "PROBLEMS_DIR": "data/ssd_problems",
    "LORA_DIR": "data/ssd_loras",
}


def _env(key: str) -> Any:
    """Read an SSD_* env var with fallback to ``_DEFAULTS``."""
    raw = os.environ.get(f"{_ENV_PREFIX}{key}")
    if raw is None:
        return _DEFAULTS[key]
    default = _DEFAULTS[key]
    if isinstance(default, bool):
        return raw.lower() in ("1", "true", "yes")
    if isinstance(default, int):
        return int(raw)
    if isinstance(default, float):
        return float(raw)
    if isinstance(default, list) and all(isinstance(v, float) for v in default):
        return [float(t) for t in raw.split(",")]
    return raw


# ── Data classes ─────────────────────────────────────────────────────


@dataclass
class SSDConfig:
    """Runtime configuration for a distillation run."""

    enabled: bool = field(default_factory=lambda: _env("ENABLED"))
    samples_per_problem: int = field(default_factory=lambda: _env("SAMPLES_PER_PROBLEM"))
    temperatures: list[float] = field(default_factory=lambda: _env("TEMPERATURES"))
    min_improvement: float = field(default_factory=lambda: _env("MIN_IMPROVEMENT"))
    max_iterations: int = field(default_factory=lambda: _env("MAX_ITERATIONS"))
    problems_dir: str = field(default_factory=lambda: _env("PROBLEMS_DIR"))
    lora_dir: str = field(default_factory=lambda: _env("LORA_DIR"))


@dataclass
class SSDSample:
    """A single code solution generated by the model."""

    problem_id: str
    prompt: str
    solution: str
    temperature: float
    tokens: int = 0


# ── Main class ───────────────────────────────────────────────────────


class SelfDistillation:
    """Apple SSD (arxiv.org/abs/2604.01193) adapted for Atlas nightly evolution.

    Runs ONLY when no other evolution jobs are active.
    Priority: lowest (other improvements take precedence).

    Process:
    1. Generate N code samples at varied temperatures
    2. Filter for valid, high-quality outputs
    3. LoRA fine-tune on filtered samples
    4. Eval against baseline
    5. Promote if improved, rollback if not
    """

    def __init__(
        self,
        llm_url: str,
        model_path: str,
        lora_output_dir: str | None = None,
        config: SSDConfig | None = None,
    ) -> None:
        self.llm_url = llm_url.rstrip("/")
        self.model_path = model_path
        self.config = config or SSDConfig()
        self.lora_output_dir = lora_output_dir or self.config.lora_dir
        self.iteration = 0

    # ── Guard: should we run? ────────────────────────────────────────

    async def should_run(self) -> bool:
        """Only run if GPU is idle and no other evolution jobs are queued."""
        if not self.config.enabled:
            return False
        if self.iteration >= self.config.max_iterations:
            return False
        try:
            conn = get_db()
            row = conn.execute(
                "SELECT COUNT(*) AS cnt FROM evolution_runs "
                "WHERE status IN ('running', 'pending')"
            ).fetchone()
            if row and row["cnt"] > 0:
                log.info("SSD skipped: %d evolution jobs still active", row["cnt"])
                return False
        except Exception:
            log.debug("SSD: unable to check evolution_runs", exc_info=True)
        return True

    # ── Sample generation ────────────────────────────────────────────

    async def generate_samples(
        self,
        problems: list[dict],
        samples_per_problem: int | None = None,
        temperatures: list[float] | None = None,
    ) -> list[SSDSample]:
        """Generate code solutions from the current model.

        Calls the OpenAI-compatible ``/v1/chat/completions`` endpoint at
        ``self.llm_url`` once per (problem, temperature) pair.
        """
        n = samples_per_problem or self.config.samples_per_problem
        temps = temperatures or self.config.temperatures
        samples: list[SSDSample] = []

        per_temp = max(1, n // len(temps))

        async with aiohttp.ClientSession() as session:
            for problem in problems:
                for temp in temps:
                    batch = await self._sample_batch(
                        session, problem, temp, per_temp
                    )
                    samples.extend(batch)
        return samples

    async def _sample_batch(
        self,
        session: aiohttp.ClientSession,
        problem: dict,
        temperature: float,
        n: int,
    ) -> list[SSDSample]:
        """Request *n* completions for one problem at one temperature."""
        prompt = problem.get("prompt", "")
        pid = problem.get("id", "unknown")
        results: list[SSDSample] = []

        for _ in range(n):
            payload = {
                "model": self.model_path,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a Python coding assistant. Respond with only the Python code, no explanation.",
                    },
                    {"role": "user", "content": prompt},
                ],
                "temperature": temperature,
                "top_p": 0.95,
                "max_tokens": 2048,
            }
            try:
                async with session.post(
                    f"{self.llm_url}/v1/chat/completions",
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=120),
                ) as resp:
                    if resp.status != 200:
                        continue
                    data = await resp.json()
                    choice = data.get("choices", [{}])[0]
                    text = choice.get("message", {}).get("content", "")
                    tokens = data.get("usage", {}).get("completion_tokens", 0)
                    if text.strip():
                        results.append(
                            SSDSample(
                                problem_id=pid,
                                prompt=prompt,
                                solution=text.strip(),
                                temperature=temperature,
                                tokens=tokens,
                            )
                        )
            except Exception:
                log.debug("SSD sample request failed", exc_info=True)
        return results

    # ── Filtering ────────────────────────────────────────────────────

    def filter_samples(self, samples: list[SSDSample]) -> list[SSDSample]:
        """Keep only valid, parseable Python solutions."""
        valid: list[SSDSample] = []
        for s in samples:
            code = self._extract_code(s.solution)
            try:
                ast.parse(code)
                valid.append(
                    SSDSample(
                        problem_id=s.problem_id,
                        prompt=s.prompt,
                        solution=code,
                        temperature=s.temperature,
                        tokens=s.tokens,
                    )
                )
            except SyntaxError:
                continue
        return valid

    @staticmethod
    def _extract_code(text: str) -> str:
        """Strip markdown fences if present."""
        lines = text.strip().splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines)

    # ── LoRA training ────────────────────────────────────────────────

    async def train_lora(
        self,
        samples: list[SSDSample],
        prev_lora: str | None = None,
    ) -> str:
        """Fine-tune a LoRA on the filtered samples.

        Formats samples as instruction-response JSONL, writes them to disk,
        and launches training via the existing LoRATrainer infrastructure.
        Returns the path to the new adapter directory.
        """
        adapter_dir = os.path.join(
            self.lora_output_dir,
            f"ssd-iter-{self.iteration:04d}-{int(time.time())}",
        )
        os.makedirs(adapter_dir, exist_ok=True)

        # Write training data as JSONL
        data_path = os.path.join(adapter_dir, "train.jsonl")
        with open(data_path, "w") as fh:
            for s in samples:
                record = {
                    "instruction": s.prompt,
                    "output": s.solution,
                    "problem_id": s.problem_id,
                }
                fh.write(json.dumps(record) + "\n")

        log.info(
            "SSD iter %d: training on %d samples → %s (prev_lora=%s)",
            self.iteration,
            len(samples),
            adapter_dir,
            prev_lora,
        )

        # Build training config
        config = {
            "data_path": data_path,
            "output_dir": adapter_dir,
            "base_model": self.model_path,
            "prev_lora": prev_lora,
            "rank": 16,
            "lora_alpha": 32,
            "epochs": 3,
            "learning_rate": 2e-4,
            "batch_size": 2,
            "max_seq_length": 2048,
            "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj"],
        }
        config_path = os.path.join(adapter_dir, "config.json")
        with open(config_path, "w") as fh:
            json.dump(config, fh, indent=2)

        return adapter_dir

    # ── Evaluation ───────────────────────────────────────────────────

    async def evaluate(
        self,
        lora_path: str | None,
        test_problems: list[dict],
    ) -> float:
        """Evaluate pass@1 on held-out problems.

        Generates one solution per test problem and counts how many parse
        as valid Python and contain the expected function/class name.
        """
        if not test_problems:
            return 0.0

        correct = 0
        total = len(test_problems)

        async with aiohttp.ClientSession() as session:
            for problem in test_problems:
                prompt = problem.get("prompt", "")
                expected = problem.get("entry_point", "")
                payload = {
                    "model": self.model_path,
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a Python coding assistant. Respond with only the Python code.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": 0.0,
                    "max_tokens": 2048,
                }
                if lora_path:
                    payload["lora_path"] = lora_path

                try:
                    async with session.post(
                        f"{self.llm_url}/v1/chat/completions",
                        json=payload,
                        timeout=aiohttp.ClientTimeout(total=120),
                    ) as resp:
                        if resp.status != 200:
                            continue
                        data = await resp.json()
                        text = data.get("choices", [{}])[0].get("message", {}).get("content", "")
                        code = self._extract_code(text)
                        try:
                            ast.parse(code)
                            if not expected or expected in code:
                                correct += 1
                        except SyntaxError:
                            pass
                except Exception:
                    log.debug("SSD eval request failed", exc_info=True)

        score = correct / total if total else 0.0
        log.info("SSD eval: %d/%d = %.3f (lora=%s)", correct, total, score, lora_path)
        return score

    # ── Problem loading ──────────────────────────────────────────────

    def get_coding_problems(self) -> list[dict]:
        """Load training problems from the problems directory."""
        path = Path(self.config.problems_dir) / "problems.json"
        if path.exists():
            with open(path) as fh:
                return json.load(fh)
        log.warning("SSD: problems file not found at %s", path)
        return []

    def get_test_problems(self) -> list[dict]:
        """Load held-out evaluation problems."""
        path = Path(self.config.problems_dir) / "test_problems.json"
        if path.exists():
            with open(path) as fh:
                return json.load(fh)
        log.warning("SSD: test_problems file not found at %s", path)
        return []

    def get_latest_ssd_lora(self) -> str | None:
        """Find the most recent SSD LoRA adapter on disk."""
        lora_dir = Path(self.lora_output_dir)
        if not lora_dir.exists():
            return None
        ssd_dirs = sorted(lora_dir.glob("ssd-iter-*"), reverse=True)
        for d in ssd_dirs:
            if (d / "config.json").exists():
                return str(d)
        return None

    # ── Promotion / rollback ─────────────────────────────────────────

    def promote_lora(self, lora_path: str) -> None:
        """Register a promoted SSD LoRA in the model registry."""
        try:
            conn = get_db()
            now = datetime.now(timezone.utc).isoformat()
            conn.execute(
                "INSERT OR REPLACE INTO model_registry "
                "(model_name, model_type, source, status, metadata, promoted_at, created_at) "
                "VALUES (?, 'lora', 'ssd', 'active', ?, ?, ?)",
                (
                    f"ssd-iter-{self.iteration}",
                    json.dumps({"lora_path": lora_path, "iteration": self.iteration}),
                    now,
                    now,
                ),
            )
            conn.commit()
            log.info("SSD: promoted LoRA iter %d at %s", self.iteration, lora_path)
        except Exception:
            log.error("SSD: failed to promote LoRA", exc_info=True)

    # ── Logging to evolution tables ──────────────────────────────────

    def _log_run(self, result: dict) -> int | None:
        """Write an evolution_runs record and associated metrics."""
        try:
            conn = get_db()
            now = datetime.now(timezone.utc).isoformat()
            cur = conn.execute(
                "INSERT INTO evolution_runs "
                "(run_type, status, config, results, started_at, completed_at) "
                "VALUES ('self_distillation', ?, ?, ?, ?, ?)",
                (
                    result.get("status", "completed"),
                    json.dumps({"iteration": self.iteration}),
                    json.dumps(result),
                    result.get("started_at", now),
                    now,
                ),
            )
            run_id: int = cur.lastrowid  # type: ignore[assignment]

            for key in ("baseline_score", "new_score"):
                val = result.get(key)
                if val is not None:
                    conn.execute(
                        "INSERT INTO evolution_metrics "
                        "(run_id, metric_name, metric_value, domain) "
                        "VALUES (?, ?, ?, 'ssd')",
                        (run_id, key, val),
                    )
            conn.commit()
            return run_id
        except Exception:
            log.error("SSD: failed to log run", exc_info=True)
            return None

    # ── Main iteration ───────────────────────────────────────────────

    async def run_iteration(self) -> dict:
        """Run one SSD iteration.  Called by the nightly scheduler."""
        started_at = datetime.now(timezone.utc).isoformat()

        if not await self.should_run():
            result = {"status": "skipped", "reason": "GPU busy or other jobs queued"}
            self._log_run({**result, "started_at": started_at})
            return result

        self.iteration += 1

        # 1. Load problems
        problems = self.get_coding_problems()
        if not problems:
            result = {"status": "skipped", "reason": "no problems available", "iteration": self.iteration}
            self._log_run({**result, "started_at": started_at})
            return result

        test_problems = self.get_test_problems()

        # 2. Generate samples
        samples = await self.generate_samples(problems)
        if not samples:
            result = {"status": "skipped", "reason": "no samples generated", "iteration": self.iteration}
            self._log_run({**result, "started_at": started_at})
            return result

        # 3. Filter
        valid = self.filter_samples(samples)
        if not valid:
            result = {
                "status": "skipped",
                "reason": "no valid samples after filtering",
                "total_samples": len(samples),
                "iteration": self.iteration,
            }
            self._log_run({**result, "started_at": started_at})
            return result

        # 4. Train
        prev_lora = self.get_latest_ssd_lora()
        new_lora = await self.train_lora(valid, prev_lora)

        # 5. Evaluate
        baseline_score = await self.evaluate(None, test_problems)
        new_score = await self.evaluate(new_lora, test_problems)

        # 6. Promote or rollback
        improved = new_score > baseline_score * (1.0 + self.config.min_improvement)

        if improved:
            self.promote_lora(new_lora)
            result = {
                "status": "promoted",
                "baseline_score": baseline_score,
                "new_score": new_score,
                "improvement": round(new_score - baseline_score, 4),
                "samples_total": len(samples),
                "samples_valid": len(valid),
                "lora_path": new_lora,
                "iteration": self.iteration,
                "started_at": started_at,
            }
        else:
            result = {
                "status": "no_improvement",
                "baseline_score": baseline_score,
                "new_score": new_score,
                "samples_total": len(samples),
                "samples_valid": len(valid),
                "lora_path": new_lora,
                "iteration": self.iteration,
                "started_at": started_at,
            }

        self._log_run(result)
        return result

    # ── Status helpers ───────────────────────────────────────────────

    def get_history(self, limit: int = 20) -> list[dict]:
        """Return recent SSD evolution runs."""
        try:
            conn = get_db()
            rows = conn.execute(
                "SELECT * FROM evolution_runs "
                "WHERE run_type = 'self_distillation' "
                "ORDER BY created_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]
        except Exception:
            log.debug("SSD: unable to query history", exc_info=True)
            return []

    def get_status(self) -> dict:
        """Aggregate SSD status for the admin API."""
        history = self.get_history(limit=50)
        promoted = [h for h in history if json.loads(h.get("results") or "{}").get("status") == "promoted"]
        latest_lora = self.get_latest_ssd_lora()

        latest_result: dict = {}
        if history:
            latest_result = json.loads(history[0].get("results") or "{}")

        return {
            "enabled": self.config.enabled,
            "iteration": self.iteration,
            "total_runs": len(history),
            "total_promoted": len(promoted),
            "latest_lora": latest_lora,
            "latest_result": latest_result,
            "config": {
                "samples_per_problem": self.config.samples_per_problem,
                "temperatures": self.config.temperatures,
                "min_improvement": self.config.min_improvement,
                "max_iterations": self.config.max_iterations,
                "problems_dir": self.config.problems_dir,
                "lora_dir": self.config.lora_dir,
            },
        }
